### ISSUE TITLE
[init] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by hwangsunwoong** [dnd-side-project/dnd-9th-2-backend#1]
## Issue 🍃
프로젝트 초기 세팅

## Todo 🌴
- [x] Issue 템플릿 추가
- [x] PR 템플릿 추가
- [x] Label 생성
- [x] Branch Rule 설정
- [x] .gitignore 설정
- [x] 프로젝트 아키텍처 설계
- [x] 팀 AWS 계정 생성
- [x] 팀 Docker Hub 계정 생성
- [x] EC2 세팅
- [x] RDS 세팅
- [x] S3 세팅
- [x] Nginx 세팅
- [x] CI/CD 세팅
- [x] Readme 초안 작성
- [x] Slack 알림 연동
- [x] 패키지 구조 분리
