### ISSUE TITLE
[feat] @Entity 클래스 구현

### ISSUE THREAD

**Issue by hwangsunwoong** [dnd-side-project/dnd-9th-2-backend#11]
## Issue 🍃
@Entity 클래스 구현

## Todo 🌴
- [x] User Entity 구현
- [x] Participation Entity 구현
- [x] Meeting Entity 구현
- [x] Feed Entity 구현
- [x] Report Entity 구현
