### ISSUE TITLE
[feat] 운영 서버 & 테스트 서버 분리

### ISSUE THREAD

**Issue by hwangsunwoong** [dnd-side-project/dnd-9th-2-backend#170]
## Issue 🍃
운영 서버 & 테스트 서버 분리

## Todo 🌴
- [x] 운영 서버 & 테스트 서버 분리 CI/CD workflow 작성
- [x] 운영 서버 EC2 인스턴스 생성
- [ ] 운영 서버 DB 생성
