### ISSUE TITLE
[refactor] 인증 사진 업로드 & 긴급소집 알람 api 예외 처리 개선

### ISSUE THREAD

**Issue by RyuKwanKon** [dnd-side-project/dnd-9th-2-backend#29]
## Issue 🍃

인증 사진 업로드 & 긴급소집 알람 api 예외 처리 개선

## Todo 🌴
- [x] 인증 사진 업로드 & 긴급소집 알람 api request field 수정
- [x] 긴급 소집 이벤트 활성화 여부 판단
- [x] 모임 참여 인원인지 판단
