### ISSUE TITLE
[feat] 1순위 api controller 구현

### ISSUE THREAD

**Issue by RyuKwanKon** [dnd-side-project/dnd-9th-2-backend#38]
## Issue 🍃

1순위 api들의 controller를 구현

## Todo 🌴
- [x] [Get] /api/member
- [x] [Post] /api/member
- [x] [Get] /api/member/detail
- [x] [Get] /api/feed
- [x] [Post] /api/feed
