### ISSUE TITLE
[feat] Meeting Status 변환 로직 구현

### ISSUE THREAD

**Issue by RyuKwanKon** [dnd-side-project/dnd-9th-2-backend#53]
## Issue 🍃

Event별로 Meeting Status를 변환하는 로직을 구현

## Todo 🌴
- [x] 모임이 확정된 경우
- [x] 긴급 소집 이벤트가 발생했을 경우
- [x] 긴급 소집이 종료된 경우
